name: Release Drafter

on:
  pull_request:
    branches: [ main, master, develop ]
    types: [ closed ]

jobs:
  draft_release:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - name: Create a release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
